# Generated by Django 5.2.6 on 2025-10-04 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Bands',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='groups',
            new_name='bands',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='addby_users',
        ),
        migrations.RemoveField(
            model_name='celebrities',
            name='addby_users',
        ),
        migrations.RemoveField(
            model_name='places',
            name='addby_users',
        ),
        migrations.RemoveField(
            model_name='sightings',
            name='addby_users',
        ),
        migrations.AddField(
            model_name='bands',
            name='addby_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celebrities',
            name='addby_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='places',
            name='addby_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sightings',
            name='addby_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
