# Generated by Django 5.2.6 on 2025-09-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrities',
            old_name='users',
            new_name='addByUsers',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='users',
            new_name='addByUsers',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='users',
            new_name='addByUsers',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='sightings',
            old_name='users',
            new_name='addByUsers',
        ),
        migrations.RenameField(
            model_name='sightings',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='dateEndGroup',
        ),
    ]
