# Generated by Django 5.2.6 on 2025-09-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_users_celebrities_addbyusers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrities',
            old_name='addByUsers',
            new_name='addby_users',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='imageURL',
            new_name='imageurl',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='celebrities',
            old_name='nickName',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='addByUsers',
            new_name='addby_users',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='addByUsers',
            new_name='addby_users',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='googlemapLink',
            new_name='googlemaplink',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='imageURL',
            new_name='imageurl',
        ),
        migrations.RenameField(
            model_name='sightings',
            old_name='addByUsers',
            new_name='addby_users',
        ),
        migrations.RenameField(
            model_name='sightings',
            old_name='arrivalDate',
            new_name='arrivaldate',
        ),
        migrations.RenameField(
            model_name='sightings',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
