# Generated by Django 5.2.6 on 2025-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_groups_bands_rename_groups_celebrities_bands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
