# Generated by Django 5.2.6 on 2025-10-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_places_latitude_places_longtitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='places',
            name='longtitude',
        ),
    ]
