# Generated by Django 5.2.6 on 2025-09-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_addbyusers_celebrities_addby_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='dateStartGroup',
            new_name='date_startgroup',
        ),
    ]
