# Generated by Django 5.2.6 on 2025-09-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_datestartgroup_groups_date_startgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='date_startgroup',
            new_name='datestartgroup',
        ),
    ]
