# Generated by Django 5.2.6 on 2025-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_startgroup_groups_datestartgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrities',
            name='imageurl',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='places',
            name='imageurl',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
