# Generated by Django 5.0.14 on 2025-10-11 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrities',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='celebrities',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='celebrities',
            name='lastname',
        ),
        migrations.AddField(
            model_name='celebrities',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrities_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='addby_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrities_addby_auth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bands',
        ),
    ]
